config/routes.rb
Rails.application.routes.draw do
  
  root to: 'invoices#new'

  resources :items
  resources :invoices

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  has_many :items, inverse_of: :invoice, dependent: :destroy
  accepts_nested_attributes_for :items, allow_destroy: true 

  def build_items(description="Enter item name/description",quantity=1,rate=0,amount=0)
      self.items.build(description: description, quantity: quantity, rate: rate, amount: amount)
  end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :invoice
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
    2.times { @invoice.build_items }
    @invoice.sales_tax = 10 
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
      
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end 
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def new_invoice_item
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:title, :company_name, :person_name, :company_address, 
                                      :city, :country, :client_company, :client_address, 
                                      :client_city, :client_country, :invoice_number, :invoice_date, 
                                      :due_date, :notes, :terms, :sub_total, :sales_tax, :total,
                                      items_attributes: [:id, :description, :quantity, :rate, :amount,
                                                         :_destroy])
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:description, :quantity, :rate, :amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/invoices_helper.rb
module InvoicesHelper
  def link_to_add_items(name,f,association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + '_fields', ff: builder)
    end
    link_to(name, '#', class: "add-items", data: { id: id, fields: fields.gsub("\n","") } )
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/invoices/_form.html.erb
<div class="container">
  <%= form_for(invoice) do |f| %>
    <% if invoice.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>
        <ul>
        <% invoice.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
      <div id="company-info">
        <div class="field">
          <%= f.text_field :company_name, placeholder: "Your Company" %>
        </div>

        <div class="field">
          <%= f.text_field :person_name, placeholder: "Your Name" %>
        </div>

        <div class="field">
          <%= f.text_field :company_address, placeholder: "Company's Address" %>
        </div>

        <div class="field">
          <%= f.text_field :city, placeholder: "City, State Zip" %>
        </div>

        <div class="field">
          <%= f.text_field :country, placeholder: "Country" %>
        </div>
      </div>

      <div id="invoice-title">
        <div class="field">
          <%= f.text_field :title, placeholder: "INVOICE" %>
        </div>
      </div>
    </div>

    <div class="row">
      <div id="client-company">
        <div class="field">
          <%= f.text_field :client_company, placeholder: "Your Client's Company" %>
        </div>

        <div class="field">
          <%= f.text_field :client_address, placeholder: "Client's Address" %>
        </div>

        <div class="field">
          <%= f.text_field :client_city, placeholder: "City, State Zip" %>
        </div>

        <div class="field">
          <%= f.text_field :client_country, placeholder: "Country" %>
        </div>
      </div>
      <div id="invoice-info">
        <div class="field">
          <%= f.label  "Invoice#" %>
          <%= f.text_field :invoice_number, placeholder: :invoice_number %>
        </div>

        <div class="field">
          <%= f.label :invoice_date %>
          <%= f.date_select :invoice_date %>
        </div>

        <div class="field">
          <%= f.label :due_date %>
          <%= f.date_select :due_date %>
        </div>
      </div>
    </div>
    
    <div class="row">
      <div id="invoice-items">
          <table id="items">
            <thead>
              <tr>
                <th>Description</th>
                <th>Quantity</th>
                <th>Rate</th>
                <th>Amount</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <%= f.fields_for :items do |items_form| %>
                <%= render 'item_fields', ff: items_form %>
              <% end %>
            </tbody>
          </table>
          <%= link_to_add_items 'New Item', f, :items %>
      </div>
    </div>
    
    <div class="row">
      <div id="invoice-total">
        <div class="field">
          <%= f.label :sub_total %>
          <%= f.text_field :sub_total, readonly: true %>
        </div>

        <div class="field">
          <%= f.label :sales_tax %>
          <%= f.text_field :sales_tax %>
        </div>

        <div class="field">
          <%= f.label :total %>
          <%= f.text_field :total, readonly: true %>
        </div>
      </div>
    </div>

    
    <div class="row">
      <div id="invoice-footer">
        <div class="field">
          <%= f.label "Notes" %><br>
          <%= f.text_area :notes, placeholder: "It was great doing business with you." %>
        </div>

        <div class="field">
          <%= f.label "Terms & Conditions" %><br>
          <%= f.text_area :terms, placeholder: "Please make the payment by the due date." %>
        </div>
      </div>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>

  <% end %>
</div>

app/views/invoices/_item_fields.html.erb
<tr data_id="<%= ff.index %>">
  <td class="item-description"><%= ff.text_area :description, placeholder: "Enter item name/description" %></td>
  <td class ="item-quantity"><%= ff.number_field :quantity %></td>
  <td class="item-rate"><%= ff.text_field :rate %></td>
  <td class="item-amount"><%= ff.text_field :amount, readonly: true %></td>
  <td class="item-remove"><%= ff.hidden_field :_destroy %></td>
  <td><%= link_to 'x', '#', class:"item-destroy" %></td>
</tr>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invoices</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Company name</th>
      <th>Person name</th>
      <th>Company address</th>
      <th>City</th>
      <th>Country</th>
      <th>Client company</th>
      <th>Client address</th>
      <th>Client city</th>
      <th>Client country</th>
      <th>Invoice number</th>
      <th>Invoice date</th>
      <th>Due date</th>
      <th>Notes</th>
      <th>Terms</th>
      <th>Sub total</th>
      <th>Sales tax</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.title %></td>
        <td><%= invoice.company_name %></td>
        <td><%= invoice.person_name %></td>
        <td><%= invoice.company_address %></td>
        <td><%= invoice.city %></td>
        <td><%= invoice.country %></td>
        <td><%= invoice.client_company %></td>
        <td><%= invoice.client_address %></td>
        <td><%= invoice.client_city %></td>
        <td><%= invoice.client_country %></td>
        <td><%= invoice.invoice_number %></td>
        <td><%= invoice.invoice_date %></td>
        <td><%= invoice.due_date %></td>
        <td><%= invoice.notes %></td>
        <td><%= invoice.terms %></td>
        <td><%= invoice.sub_total %></td>
        <td><%= invoice.sales_tax %></td>
        <td><%= invoice.total %></td>
        <td><%= link_to 'Show', invoice %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form', invoice: @invoice %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
      <div id="company-info">
        <div class="field">
          <input type="text" name="company_name" value="<%= @invoice.company_name %>"> 
        </div>

        <div class="field">
          <input type="text" name="person_name" value="<%= @invoice.person_name %>"> 
        </div>

        <div class="field">
          <input type="text" name="company_address" value="<%= @invoice.company_address %>"> 
        </div>

        <div class="field">
          <input type="text" name="city" value="<%= @invoice.city %>"> 
        </div>

        <div class="field">
          <input type="text" name="country" value="<%= @invoice.country %>"> 
        </div>
      </div>

      <div id="invoice-title">
        <div class="field">
          <input type="text" name="title" value="<%= @invoice.title %>"> 
        </div>
      </div>
    </div>

    <div class="row">
      <div id="client-company">
        <div class="field">
          <input type="text" name="client_company" value="<%= @invoice.client_company %>"> 
        </div>

        <div class="field">
          <input type="text" name="client_address" value="<%= @invoice.client_address %>"> 
        </div>

        <div class="field">
          <input type="text" name="client_city" value="<%= @invoice.client_city %>"> 
        </div>

        <div class="field">
          <input type="text" name="client_country" value="<%= @invoice.client_country %>"> 
        </div>
      </div>
      <div id="invoice-info">
        <div class="field">
          Invoice# <input type="text" name="invoice_number" value="<%= @invoice.invoice_number %>"> 
        </div>

        <div class="field">
          Invoice Date <input type="text" name="invoice_date" value="<%= @invoice.invoice_date %>"> 
        </div>

        <div class="field">
          Due Date <input type="text" name="due_date" value="<%= @invoice.due_date %>">
        </div>
      </div>
    </div>
    
    <div class="row">
      <div id="invoice-items">
          <table id="items">
            <thead>
              <tr>
                <th>Description</th>
                <th>Quantity</th>
                <th>Rate</th>
                <th>Amount</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @invoice.items.each do |item| %>
                <tr>
                  <td class="item-description"><textarea name="description"><%= item.description %></textarea></td>
                  <td class ="item-quantity"><input type="text" name="quantity" value="<%= item.quantity %>"></td>
                  <td class="item-rate"><input type="text" name="rate" value="<%= item.rate %>"></td>
                  <td class="item-amount"><input type="text" name="amount" value="<%= item.amount %>"></td>
                </tr>
              <% end %>
            </tbody>
          </table>
      </div>
    </div>
    
    <div class="row">
      <div id="invoice-total">
        <div class="field">
          Sub total: <input type="text" name="sub_total" value="<%= @invoice.sub_total %>">
        </div>

        <div class="field">
          Sales tax: <input type="text" name="sales_tax" value="<%= @invoice.sales_tax %>">
        </div>

        <div class="field">
          Total: <input type="text" name="total" value="<%= @invoice.total %>">
        </div>
      </div>
    </div>

    
    <div class="row">
      <div id="invoice-footer">
        <div class="field">
          Notes<br>
          <textarea name="notes"><%= @invoice.notes %></textarea>
        </div>

        <div class="field">
          Terms &amp; Conditions<br>
          <textarea name="terms"><%= @invoice.terms %></textarea>
        </div>
      </div>
    </div>
</div>


<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table id="items">
  <thead>
    <tr>
      <th>Description</th>
      <th>Quantity</th>
      <th>Rate</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

      <tr>
        <td class="item-description"><%= f.text_area :description, placeholder: "Enter item name/description" %></td>
        <td class ="item-quantity"><%= f.number_field :quantity %></td>
        <td class="item-rate"><%= f.text_field :rate %></td>
        <td class="item-amount"><%= f.text_field :amount %></td>
      </tr>

  </tbody>
</table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Quantity</th>
      <th>Rate</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.description %></td>
        <td><%= item.quantity %></td>
        <td><%= item.rate %></td>
        <td><%= item.amount %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @item.quantity %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @item.rate %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @item.amount %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZohoInvoice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>